extends Node

signal player_health_changed
signal durability_changed
signal active_slot_changed
signal weapon_in_slot_changed
signal resource_count_changed
signal ingredients_changed
signal crafting_menu_state_changed
